[package]
name = "glass"
version = "0.1.0"
authors = ["Arpith Siromoney <arpith@feedreader.co>"]

[dependencies]
hyper = "0.9"
html5ever = "0.5.3"
string_cache = "0.2.18"
tendril = "0.2.2"
cssparser = "0.5.7"
piston_window = "0.51"
find_folder = "0.3"
conrod = "0.40.0"
